config-version: 4

group-permission: 'group.%s'

assigned-group-permission: ''

default-group: default

default-track: default

dump-directory: zPermissions-dumps

default-temp-permission-timeout: 60

tracks:
  default:
  - default
  - somegroup
  - someothergroup

cache-max-idle: 180

cache-max-ttl: 600

cache-size: 1000

kick-on-error: true

kick-ops-on-error: false

region-support: true

debug: false
