# Groups may have a group permission node automatically assigned to their
# members. This is the name of that permission node. It must be a string
# suitable for Java's String.format() with one argument: the group name.
# Omit or leave blank ('') to disable this feature.
group-permission: 'group.%s'

# The default group. Players that are not explicitly members of any group
# are placed in this group.
default-group: default

# The default track. When the track name is omitted while using the /promote
# and /demote commands, this is the track used.
default-track: default

# Directory (relative to the server root) where to load/store dumps.
dump-directory: zPermissions-dumps

# Default timeout for temporary permissions, in seconds
default-temp-permission-timeout: 60

# Track definitions. Each key should be the name of the track. The value
# should be a list of group names in ascending order.
tracks:
  default:
  - default
  - somegroup
  - someothergroup
