config-version: 9

database-support: true

region-support: true

group-permission: 'group.%s'

assigned-group-permission: ''

assigned-groups-can-include-default: true

default-group: default

default-track: default

dump-directory: zPermissions-dumps

default-temp-permission-timeout: 60

tracks:
  default:
  - default
  - somegroup
  - someothergroup

kick-on-error: true

kick-ops-on-error: false

auto-refresh-interval: -1

opaque-inheritance: true

rank-admin-broadcast: true

debug: false
