name: zPermissions
version: ${version}
main: org.tyrannyofheaven.bukkit.zPermissions.ZPermissionsPlugin
description: Superperms implementation with Bukkit database backend
author: ZerothAngel
database: true

commands:
  permissions:
    description: Top-level command for zPermissions
    aliases: [perm, p]
  promote:
    description: Promote a player up a rank
    aliases: rankup
    permission: zpermissions.promote
  demote:
    description: Demote a player down a rank
    aliases: rankdown
    permission: zpermissions.demote
  setrank:
    description: Set the rank of a player
    permission: zpermissions.setrank

permissions:
  zpermissions.*:
    description: All-inclusive permission for zPermissions
    default: op
    children:
      zpermissions.player: true
      zpermissions.group: true
      zpermissions.list: true
      zpermissions.check: true
      zpermissions.check.other: true
      zpermissions.reload: true
      zpermissions.export: true
      zpermissions.import: true
      zpermissions.promote: true
      zpermissions.promote.*: true
      zpermissions.demote: true
      zpermissions.demote.*: true
      zpermissions.setrank: true
      zpermissions.setrank.*: true
      zpermissions.cache: true
  zpermissions.player:
    description: Allows use of the /permissions player command
  zpermissions.group:
    description: Allows use of the /permissions group command
  zpermissions.list:
    description: Allows use of the /permissions list command
  zpermissions.check:
    description: Allows use of the /permissions check command
  zpermissions.check.other:
    description: Allows use of the /permissions check command on others
  zpermissions.reload:
    description: Allows use of the /permissions reload command
  zpermissions.export:
    description: Allows use of the /permissions export command
  zpermissions.import:
    description: Allows use of the /permissions import command
  zpermissions.promote:
    description: Allows use of the /promote command
  zpermissions.promote.*:
    description: Allows use of /promote on all tracks
  zpermissions.demote:
    description: Allows use of the /demote command
  zpermissions.demote.*:
    description: Allows use of /demote on all tracks
  zpermissions.setrank:
    description: Allows use of the /setrank command
  zpermissions.setrank.*:
    description: Allows use of /setrank on all tracks
  zpermissions.cache:
    description: Allows use of the /permissions cache command
